import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ['latin']}); //importa a fonte


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>

        {children}

        <Toaster position="top-right"/>

      </body>
    </html>
  );
}

//o Toaster é usado no login e no cadastro, ele tem que compor o corpo do layout 
// para aparecer nessas páginas quando elas assumirem o lugar de {children}
//children troca toda hora, é constantemente roteado
